Repository KAU-OSS-2024-E/OSS-tic-tac-teo, pull requests merged in 2024-06, with the labels that each got.

#32 CleanCode/Change board to 2D array#27
  headers/game_logic.h
  headers/game_rules.h
  src/game_logic.c
  src/game_rules.c
  src/main.c
Labels: CleanCode

#40 DivisionCompile/Cmake#39
  .gitignore
  CMakeLists.txt
  DEVELOPE.md
  README.md
Labels: DivisionCompile

#41 FixBug/Fix easy mode and menu#38
  headers/main_menu.h
  src/game_logic.c
  src/main_menu.c
Labels: FixBug

#42 37 clean code 헤더 파일 관리
  DEVELOPE.md
  headers/game_logic.h
  headers/main_menu.h
  headers_for_linux/env.h
  headers_for_win/env.h
  src/game_logic.c
  src/game_rules.c
  src/main.c
  src/main_menu.c
  src_for_linux/env.c
  src_for_linux/move_cursor.c
  src_for_win/env.c
  src_for_win/move_cursor.c
Labels: CleanCode

#44 43 clean code linux 컴파일 지원
  DEVELOPE.md
  TicTacToe_linux
  headers/move_cursor.h
  headers_for_linux/env.h
  headers_for_win/move_cursor.h
  src/game_logic.c
  src/main.c
  src/main_menu.c
  src_for_linux/env.c
  src_for_linux/move_cursor.c
Labels: CleanCode, DivisionCompile

#46 45 divisioncompile 해더 파일 최적화
  DEVELOPE.md
  headers/env.h
  headers_for_win/env.h
  headers_for_win/move_cursor.h
  src_for_win/env.c
  src_for_win/move_cursor.c
Labels: CleanCode, DivisionCompile

#52 CleanCode/delete magic number#35
  TicTacToe_linux
  headers/game_constants.h
  src/game_logic.c
  src/game_rules.c
  src/main.c
Labels: CleanCode

#55 Add feature/Add speed mode menu#47
  DEVELOPE.md
  TicTacToe_linux
  headers/env.h
  headers/game_constants.h
  headers/game_logic.h
  headers/main_menu.h
  headers_for_win/env.h
  headers_for_win/move_cursor.h
  src/game_logic.c
  src/game_rules.c
  src/main.c
  src/main_menu.c
  src_for_win/env.c
  src_for_win/move_cursor.c
Labels: AddFeature

#57 AddFeature/Add speed mode menu#47
  .vscode/settings.json
  src/main_menu.c
Labels: AddFeature

#59 FixBug/modify multiplay output#58
  src/main_menu.c
Labels: FixBug

#61 AddFeature/Add speed mode #47
  headers/game_logic.h
  headers/main_menu.h
  src/game_logic.c
  src/main.c
  src/main_menu.c
Labels: AddFeature

#67 Cleancode/refactoring#64
  DEVELOPE.md
  headers/console_output.h
  headers/env.h
  headers/game_logic.h
  headers/game_menu.h
  headers/game_rules.h
  headers/main_menu.h
  src/console_output.c
  src/game_logic.c
  src/game_menu.c
  src/game_rules.c
  src/main.c
  src/main_menu.c
Labels: Docs, AddFeature, CleanCode, DivisionCompile

#69 FixBug/Fix menu select #68
  headers/game_logic.h
  src/console_output.c
  src/game_logic.c
  src/game_menu.c
Labels: FixBug
