Repository KAU-OSS-2024-E/OSS-tic-tac-teo, pull requests merged in 2024-05, with the labels that each got.

#1 Seungwoo test
  TicTacToe.c
Labels: good first issue

#4 menu check
  TicTacToe.c
Labels: enhancement

#5 test 1
  TicTacToe.c
Labels: help wanted

#3 main_func check_2
  TicTacToe.c
Labels: help wanted

#8 Test 2
  TicTacToe.c
  git
Labels: help wanted

#10 Seungwoo
  DEVELOPE.md
  TicTacToe.c
  game_rules.h
  win_game.c
Labels: documentation, enhancement

#12 Seungwoo
  DEVELOPE.md
  Makefile
  TicTacToe.o
  win_game.c
  win_game.o
Labels: documentation, enhancement

#16 posswin -> find_win_position
  src/game_logic.c
  src/game_rules.c
Labels: CleanCode

#21 17 bug1 find possible position debugging
  headers/game_rules.h
  src/game_logic.c
Labels: FixBug, CleanCode, Test

#23 Docs/updatePRtemplate#19
  .github/pull_request_template.md
Labels: Docs
